### ISSUE TITLE
Possible error in JWS.jose_header

### ISSUE THREAD

**Issue by tiran** [latchset/jwcrypto#105]
Static code analysis is complaining about some unusual code. I'm not familiar enough with JWS standard to triage the issue. Is `` if 'protected' in obj:`` correct or should it rather be `` if 'protected' in o:``?

```
1. jwcrypto-0.4.2/jwcrypto/jws.py:489: original: ""protected" in obj" looks like the original copy.
2. jwcrypto-0.4.2/jwcrypto/jws.py:498: copy_paste_error: "obj" in ""protected" in obj" looks like a copy-paste error.
3. jwcrypto-0.4.2/jwcrypto/jws.py:498: remediation: Should it say "o" instead?
#   496|               for o in obj['signatures']:
#   497|                   jh = dict()
#   498|->                 if 'protected' in obj:
#   499|                       p = json_decode(o['protected'])
#   500|                       jh = self._merge_headers(jh, p)
```

https://github.com/latchset/jwcrypto/blob/ccee40277c1eb46a6ca3d4e92d8267ae68bd05fc/jwcrypto/jws.py#L494-L501

**Comment by simo5** [comment]
It should be in o, good catch, love static analysis, patch forthcoming
