### ISSUE TITLE
Why LGPL?

### ISSUE THREAD

**Issue by matt-10e** [latchset/jwcrypto#112]
This is a nice library, but LGPL makes the lawyers nervous.  Why not something more permissive like BSD or MIT?

**Comment by simo5** [comment]
Because we like the LGPL, if your lawyers are nervous at a so well known license, maybe change lawyers :-)

**Comment by matt-10e** [comment]
Thanks for the quick response, we just ended up going with this library instead: https://github.com/mpdavis/python-jose
