### ISSUE TITLE
CryptographyDeprecationWarning in jwa.py

### ISSUE THREAD

**Issue by julb** [latchset/jwcrypto#113]
When using JWCrypto methods on my Python 3.6.4 installation, the process raises CryptographyDeprecationWarnings due to deprecated methods :

/usr/local/lib/python3.6/dist-packages/jwcrypto/jwa.py:153: CryptographyDeprecationWarning: encode_rfc6979_signature is deprecated and will be removed in a future version, use encode_dss_signature instead.
  int(hexlify(r), 16), int(hexlify(s), 16))

/usr/local/lib/python3.6/dist-packages/jwcrypto/jwa.py:144: CryptographyDeprecationWarning: decode_rfc6979_signature is deprecated and will be removed in a future version, use decode_dss_signature instead.
  r, s = ec_utils.decode_rfc6979_signature(signature)

For future releases, it would be interesting to fix this so the library will work with future Python releases.

Btw, your library is very awesome :)

**Comment by simo5** [comment]
Thanks,
what python-cryptography version are you using ?

**Comment by julb** [comment]
Pip installs cryptography V2.2.2

You can find the warning on the tagged version [here](https://github.com/pyca/cryptography/blob/2.2.2/src/cryptography/hazmat/primitives/asymmetric/utils.py)

**Comment by simo5** [comment]
thanks I still had 2.0.2 on the machine I tested, it does have the new functions, but the deprecation warning was not showing for some reason... #114 will handle this

**Comment by julb** [comment]
Thanks for the quick fix 👍 
Looking forward for the next release!
