### ISSUE TITLE
Attempting to use a bytestring as a secret breaks JWK

### ISSUE THREAD

**Issue by freyley** [latchset/jwcrypto#120]
I'm attempting to decrypt a JWE token generated by someone else using the Ruby JOSE library, and they chose to encrypt it not with their secret, but with the SHA256 digest of their secret. 

In Ruby, this works fine, and can be used to generate a payload.

In Python, with jwcrypto, taking the secret and generating a SHA256 digest generates a bytestring. Handing a bytestring to JWK does not error, but handing that JWK object to JWE.decrypt() blows up with a UnicodeDecodeError.

Pull request with a test showing the issue and a bad solution to discuss shortly.

**Comment by simo5** [comment]
From RFC 7518:
```
6.4.1.  "k" (Key Value) Parameter

   The "k" (key value) parameter contains the value of the symmetric (or
   other single-valued) key.  It is represented as the base64url
   encoding of the octet sequence containing the key value.
```

Therefore JWK will never accept as valid a bytestring, you have to convert it tio a base64url encoded string first.

**Comment by freyley** [comment]
So, the Ruby JOSE library is just doing it wrong?

I mean the thing is, interoperability is a pretty critical aspect of using JOSE, and I'm not an expert. I don't suppose there's a mailing list where all the JOSE library authors hang out and can discuss this?

**Comment by simo5** [comment]
No I mean you are using it wrong, in your example you should do this:
```
key = jwk.JWK(kty='oct', k=base64_urlencode(hashlib.sha256(unhashed_secret).digest()))
```

Or something like that

**Comment by freyley** [comment]
@simo5 oh, I see! sorry, I guess I wasn't understanding. I will attempt that and see if it works to decrypt their token.

**Comment by freyley** [comment]
@simo5 that does work. I can offer my PR as just the test, then.

**Comment by simo5** [comment]
I included an equivalent (but shorter) test in jwcrypto/tests.py
Thanks a lot for raising this (missing) validation bug.
