### ISSUE TITLE
[Question] Could JWS infer the `alg` from the key type?

### ISSUE THREAD

**Issue by rdrey** [latchset/jwcrypto#125]
Hey! Great project, thanks! Question in the subject :P

If I send an RSA key as the argument, we can definitely use RS256 (probably has the widest support), for example, right?

I haven't tried EC keys or HMACs yet, but would this idea be bad for some reason? Or could I start working on a PR?

**Comment by simo5** [comment]
So you want to use a "default" algorithm when creating JWS tokens based on the key type provided ?

**Comment by rdrey** [comment]
@simo5 yeah, that's the idea/plan. I'm up for suggestions which `alg` to use for which key-type, for now my code just does 

```py
            # TODO: Need to add more 'alg' type lookups
            'alg': 'RS256' if jwk_key.key_type == 'RSA' else None,
```

**Comment by simo5** [comment]
See jwa.py, the _get_key() or _check_key() function of the various base classes tells you what key type is required. I am not yet entirely sure that choosing the alg automatically is a good idea though.
In what case would you not want to specify the algorithm to use ?

**Comment by rdrey** [comment]
I'm building a client that sends JWS-encoded payloads and I'd like to make it "customer key-type agnostic". (I know the API won't accept symmetric keys, but I don't want to lock my customer's key type to just RSA.)

I'll definitely derive the `'alg'` from the key to make it more user-friendly (customers could be following tutorials and not understand much about crypto), so I'm just wondering if the JWS library should offer that at a lower level.

**Comment by simo5** [comment]
Sounds like a fine thing to do in an application, less so in the library.
Also why do you say symmetric keys are not accepted ?

**Comment by rdrey** [comment]
> Sounds like a fine thing to do in an application, less so in the library.

Coolio, I'll close this for now, thanks. It's really little code in any case.

> Also why do you say symmetric keys are not accepted ?

The "asymmetric keys only" requirement is set by the protocol/service (ACME / LetsEncrypt), so my client would inspect the `.key_type` in any case to enforce that.
