### ISSUE TITLE
Implement support for CFRG Curves (Ed/X-25519/448)

### ISSUE THREAD

**Issue by simo5** [latchset/jwcrypto#127]
RFC 8037 defines how to use CRFG curves Ed25519 and Ed448 for EdDSA digital signatures and X25519 and X448 for ECDH key exchange.

**Comment by simo5** [comment]
Blocked on:
https://github.com/pyca/cryptography/issues/3509
https://github.com/pyca/cryptography/issues/4136

**Comment by simo5** [comment]
See https://github.com/simo5/jwcrypto/tree/rfc8037 for a start

**Comment by andrewmackie** [comment]
Is the [support for Ed25519 in cryptography](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ed25519/) now sufficient to support it in jwcrypto, please?

**Comment by simo5** [comment]
It should be sufficient, I just need time to pick up the work I did back then and finish it, is in some branch somewhere in my devel laptop :-)

However if you feel brave and want to try to contribute, that's also welcome!

**Comment by andrewmackie** [comment]
Thanks Simo. I've forked the repo and will see what I can do.

**Comment by andrewmackie** [comment]
I've got some working code in [jwk.py](https://github.com/andrewmackie/jwcrypto/blob/master/jwcrypto/jwk.py) - enough to create an Ed25519 key and check it exports okay.

Note that:
- the key type is 'OKP' in keeping with [RFC 8037](https://tools.ietf.org/html/rfc8037#page-9).
- I have a kluge in [lines 388 and 391](https://github.com/andrewmackie/jwcrypto/blob/master/jwcrypto/jwk.py#L388)  - I export the keys with a raw encoding and then run base64url_encode on them - do you know the right encoder to extract them as base64url in the first place?

I'll work through the other modules tomorrow and make a pull request when I'm done.

**Comment by andrewmackie** [comment]
FYI I also hard-coded Ed25519 in for now (all 'OKP' key types must be Ed25519 curves), but there are primitives for ed448, x448 and x25199 available and I'll extend it.

**Comment by andrewmackie** [comment]
I've supported ed448 in jwk.py (I won't add x448 or x25199 for now).

I'm now stuck on jwa.py - where do the Python implementations of the EdDSA algorithms come from, please?

**Comment by simo5** [comment]
@andrewmackie you may want to cherry-pick from this branch:
https://github.com/simo5/jwcrypto/tree/rfc8037

**Comment by andrewmackie** [comment]
I have submitted a [pull request](https://github.com/latchset/jwcrypto/pull/154) with my changes.

This has only limited support for X25519 and X448 - they are covered in jwk.py but the key exchange is not handled in jwa.py. There's an exchange() method for the private key in backends\openssl\x25519.py but I wasn't sure how to handle it and have left it for people who know what they're doing.

**Comment by simo5** [comment]
I am curious, why the PR churn ?

**Comment by simo5** [comment]
exchange() is used for EcDH, but don't worry, if you do not feel confident adding X25519/X448 support, feel free to leave them out completely, and I'll add it later.

**Comment by andrewmackie** [comment]
Sorry - this is my first-ever pull request and I'm still learning how it works.

I am very much aware that most people's first PR isn't to a *cryptographic* library, so I'm treading carefully, possibly too carefully ...

Thanks for you patience with a noob!



On 27 March 2019 11:54:08 pm AEDT, Simo Sorce <notifications@github.com> wrote:
>I am curious, why the PR churn ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/latchset/jwcrypto/issues/127#issuecomment-477139474

-- 
Sent from my phone.

**Comment by simo5** [comment]
No worries, shout if you need help.

**Comment by simo5** [comment]
Ed25519 and Ed448 done via #155
