### ISSUE TITLE
JWE: unwrap key with multiples recipients spams decryptlog

### ISSUE THREAD

**Issue by JonathanHuot** [latchset/jwcrypto#129]
When decrypting a JWE with multiple recipients (JWE JSON serialization), the library should try to unwrap  only once, based on a `kid`. If no information is provided at all, only then it can fallback to unwrap all the encrypted keys.

It is a performance issue and also it leads to spam the  `decryptlog`. The current `decrypt` implementation loops on every recipients and tries to `unwrap` each recipient with the given key. Only one attempt will succeed and others add a "Failed" in `decryptlog` for each failed attempts. 

I think `jwcrypto` users should provide a list of keys mapped to their `kid` (or dict?) to have a chance to solve this issue. Also, it would be great to have feedback from the other usages as well ?

Many thanks for this great library.

Note the relevant section of the RFC:
``` 
        Note that when there are
        multiple recipients, each recipient will only be able to decrypt
        JWE Encrypted Key values that were encrypted to a key in that
        recipient's possession.  It is therefore normal to only be able
        to decrypt one of the per-recipient JWE Encrypted Key values to
        obtain the CEK value.```

**Comment by simo5** [comment]
I am looking at this, also with the intention of supporting passing in a JWKSet, and boy is it annoying.
Is the decryptlog spamming an issue only if decryption fails?
Or should we always clear it if one of the keys succeeds ?
The thing is that looking at implementation the easiest way to go through 'kid's is to raise a generic error about 'kid' not matching, but with a JWKSet and, say 3 keys and 3 recipents, the worst case is a decryptlog with 8 "no matching KID' messages, and finally success ...

**Comment by simo5** [comment]
Also should we have 'kid' in both the token and the key, but for whatever reason we do not find a match, should we go back and try anyway as if 'kid' were not present, just on the off-chance that the kid for the right keys is different between producer and consumer ?
Sounds like this can happen and should be handled...
