### ISSUE TITLE
Wrong condition for checking claims?

### ISSUE THREAD

**Issue by papayuca** [latchset/jwcrypto#135]
https://github.com/latchset/jwcrypto/blob/d0c3ee2797d1321304a423a46dac620e238f98f3/jwcrypto/jwt.py#L343

Should it not be:
`if self._check_claims is not None:`

Otherwise if exp claim is in the past, no error whil be raised.

**Comment by simo5** [comment]
No,
the default _check_default_claims() checks for valid times only in the default case, ie when no claims have been explicitly passed in, when claims to check have been explicitly passed in then we check exp and nbf only if they have been explicitly provided, later on

The code could make it clearer ...
