### ISSUE TITLE
Using python-gnutls for pkcs11

### ISSUE THREAD

**Issue by stefanberger** [latchset/jwcrypto#140]
I would like to be able to use the TPM for signing or JWTs. For this I have wrapped a few private key related gnutls functions to be able to access a TPM key that can then be used for signing. Is python-gnutls an acceptable path for you?

**Comment by simo5** [comment]
In what way ?
jwcrypto uses python-cryptography for all low level crypto, and I am afraid python-cryptography uses only openssl the se days (used to be able to use multiple backends but I do not think that is true anymore).

**Comment by stefanberger** [comment]
I guess you answered my question. GnuTLS support for using the TPM would be wrong then.

**Comment by simo5** [comment]
Right.
I think three things need to happen to be able to use TPM with jwcrypto:
1) support in python-cryptography
2) probably some data in JWKs (maybe special kid format ?) to indicate the key is in TPM.
3) Code changes to make it possible to use an external key. At least some of the code assums direct access to key material, so appropriate changes will have to made.

**Comment by stefanberger** [comment]
It should use the PKCS#11 interface, which is hopefully already supported in python-cryptography.

For now I would only have a very narrow use case where I would like to use/add a JWK key import function to import a TPM private key via a (GnuTLS) key URI (kind of PKCS#11 URI in TPM case) and use the device for signing a JWT.

**Comment by simo5** [comment]
I do not think python-cryptography has support for PKCS#11, probably due to the fact it is a separate engine for openssl ...
I am going to close this issue for now, once pyca can support pkcs#11 we can open a better targeted issue for jwcrypto
