### ISSUE TITLE
Cannot validate JWT with no kid in its header

### ISSUE THREAD

**Issue by Esenin** [latchset/jwcrypto#143]
Hi folks! First of all, I appreciate your library a lot. 

Recently, I ran into the following issue. A 3rd party system provides us a JWT which we want to verify. We have no means of changing implementation on the provider side. 
They send us a token which does not contain a _kid_ in its header. According to my understanding of RFC 7515, 7517 that field is optional. 

However, I got an exception on `jwt = JWT(jwt=token, key=jwks)`

```
  File "<...>/python3.6/site-packages/jwcrypto/jwt.py", line 474, in deserialize
    raise JWTMissingKeyID('No key ID in JWT header')

jwcrypto.jwt.JWTMissingKeyID: No key ID in JWT header
```

As I checked the code it's quite obvious that it does not work without "kid" in a header:
`./eggs/jwcrypto-0.6.0-py2.7.egg/jwcrypto/jwt.py:`  **in** `def deserialize(self, jwt, key=None):`
```python
        if key is None:
            self.token.deserialize(jwt, None)
        elif isinstance(key, JWK):
            self.token.deserialize(jwt, key)  # <-- Also why it's only deserialized here but not validated? 
        elif isinstance(key, JWKSet):
            self.token.deserialize(jwt, None)
            if 'kid' not in self.token.jose_header:
                raise JWTMissingKeyID('No key ID in JWT header')

            token_key = key.get_key(self.token.jose_header['kid'])
            if not token_key:
                raise JWTMissingKey('Key ID %s not in key set'
                                    % self.token.jose_header['kid'])

            if isinstance(self.token, JWE):
                self.token.decrypt(token_key)
            elif isinstance(self.token, JWS):
                self.token.verify(token_key)
            else:
                raise RuntimeError("Unknown Token Type")
```

How we can deal with it? In case if there is no certain "kid" in a token's header could we perhaps iterate over all available `jwk.JWK` in a `jwk.JWKSet` until for one of them the signature matches. And if neither have worked out then throw an exception. I propose to add this kind of logic in the library. What do you think? 

Currently, a workaround is possible. E.g.
```python
for i, k in enumerate(jwks):
    try:
        jwt = JWT(jwt=token, key=k)
    except Exception as e:
        if (i == len(jwks) - 1):
            raise
        jwt = None

```
But it's not very nice because
1. from the code snippet above-above you can see that if key is just a JWK then no verification happens. I don't quite understand why.
2.  it breaks a nice encapsulation we used to have here. In general our use case looks like the following.
```python
# our use case 
response = requests.get(url)
jwks = JWKSet.from_json(response.text)
jwt = JWT(jwt=token, key=jwks)
claims = json.loads(jwt.claims)
...
```

```cpp
/* It might be that I misunderstood smth, I'm new to the JWT stuff overall */
```

**Comment by Esenin** [comment]
> from the code snippet above-above you can see that if key is just a JWK then no verification happens. I don't quite understand why.

^ I have to withdraw that point of mine since JWS actually does the validation in its `deserialize` method. I missed this place earlier. 

>  but I wonder how to report issues if all keys fail

Well, I cannot provide a good advice here because I don't have enough experience with the ecosystem yet. Maybe a new type of exception inherited from `InvalidJWKType` would work if neither of the keys in set match the algorithm in a header. But if at least one of the keys matched the requirements and none of the matched keys did the job then `InvalidJWSSignature`. That's my first guess based the code I've seen so far.

**Comment by simo5** [comment]
@Esenin take a look at pull #144 and let me know if this meets your expectations.

**Comment by Esenin** [comment]
@simo5 checked. looks good to me!
