### ISSUE TITLE
JWE accept dictionary as payload

### ISSUE THREAD

**Issue by aaeronn** [latchset/jwcrypto#166]
Currently only plaintext is used as payload but what if I want to encrypt dictionary data as a payload

**Comment by eirnym** [comment]
I encode it by myself as I can fully control how it encodes/decodes it. E.g, use dates, Decimals and other types if needed.

**Comment by simo5** [comment]
from jwcrypto.common import json_encode

payload = json_encode({"my":"structured payload"})

Then payload is plaintext and you control exactly its format in all situation so you can be compatible with how a different implementation may deal with structured data if you need to.
