### ISSUE TITLE
Bad JWT signature

### ISSUE THREAD

**Issue by slavkoja** [latchset/jwcrypto#172]
I am not sure, if i did all right, but when i follow provided examples to generate signed JWT (0.6.0), the verification fails with `pyjwt` (1.7.1) and on https://jwt.io/ too.

Here is what i did:
```python
import jwt as jjwt
from jwcrypto import jwt, jwk, jws

k = "123456"

key = jwk.JWK(kty="oct",k=k)
algo = "HS256"
payload = {"info": "I'm a signed token"}

j = jjwt.encode(payload, k, algorithm=algo).decode()

t = jwt.JWT(header={"alg": algo, "typ":"JWT"},
            claims=payload)
t.make_signed_token(key)

print("JWTs:")
print("   jwt:     ", j)
print("   jwcrypto:", t.serialize())

print("\nDecode by jwt")
try:
    jjwt.decode(j, k, algorithms=algo)
    print("   ok  jwt -> jwt")
except jjwt.exceptions.InvalidSignatureError:
    print("   err jwt -> jwt")

try:
    jjwt.decode(t.serialize(), k, algorithms=algo)
    print("   ok  jwt -> jwt")
except jjwt.exceptions.InvalidSignatureError:
    print("   err jwcrypto -> jwt")

print("\nDecode by jwcrypto")
try:
    jwt.JWT(key=key, jwt=j)
    print("   err jwt -> jwcrypto")
except jws.InvalidJWSSignature:
    print("   err jwt -> jwcrypto")

try:
    jwt.JWT(key=key, jwt=t.serialize())
    print("   ok  jwcrypto -> jwcrypto")
except jws.InvalidJWSSignature:
    print("   err jwcrypto -> jwcrypto")
```
The output is:
```
JWTs:
   jwt:      eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbmZvIjoiSSdtIGEgc2lnbmVkIHRva2VuIn0.6GKQC7tu4wzOdArW5KttM-vSNhSj69jYB6blldvsaIc
   jwcrypto: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmZvIjoiSSdtIGEgc2lnbmVkIHRva2VuIn0.J0LizeVgrQwBYCCLIot3lXdkYxxFGl2VqOP6fM0t60o

Decode by jwt
   ok  jwt -> jwt
   err jwcrypto -> jwt

Decode by jwcrypto
   err jwt -> jwcrypto
   ok  jwcrypto -> jwcrypto
```
For now, i am not sure, which library does bad signature, but token from `pyjwt` can be verified on https://jwt.io/, the one from `jwcrypto` cannot.

**Comment by simo5** [comment]
I am investigating, not clear what causes this.
There must be some encoding difference when passing data to the HMAC function.

**Comment by simo5** [comment]
I found the issue,
replace:
key = jwk.JWK(kty="oct",k=k)
with 
key = jwk.JWK(kty="oct",k=jwcrypto.common.base64url_encode(k))

Your JWK invocation didn't fail only because you used a text key which is also "valid" base64 (decodes to "m") 
In fact if you use "m" as the secret in jwt.io you will see that the above signature does verify.

**Comment by slavkoja** [comment]
It happens with [nginx-jwt-module](https://github.com/max-lt/nginx-jwt-module) too. I can authenticate with token from `pyjwt`, but not with token from `jwcrypto`. The tokens generated by the same script as above.

**Comment by slavkoja** [comment]
Thanks, it works
