### ISSUE TITLE
Commercial Usage

### ISSUE THREAD

**Issue by hi2rashid** [latchset/jwcrypto#174]
We are using this module  in our internal application with Django.

Can you please confirm if its okay to be used commercially.

Thank you in advance

**Comment by simo5** [comment]
I am not sure what you are asking and I am not a lawyer, if you have license questions I suggest consulting with one. The license for this project is in the LICENSE file.

**Comment by eirnym** [comment]
@hi2rashid if you open the [LICENCE](https://github.com/latchset/jwcrypto/blob/master/LICENSE) file, GitHub will show what you can, what you can't do with it.
