### ISSUE TITLE
make leeway and validitity configurable

### ISSUE THREAD

**Issue by jonas-weismueller-jdas** [latchset/jwcrypto#179]
Hi,
would it be possible to make leeway and validity configurable in the constructor https://github.com/latchset/jwcrypto/blob/master/jwcrypto/jwt.py#L154 ?

**Comment by simo5** [comment]
In principle we could, what is the use case ?

**Comment by jonas-weismueller-jdas** [comment]
I want to set another exp value rather then the default one 600 (validity) + 60 (leeway). I want to have a tokenn, which expires e.g. in 5 minutes rather than 11 minutes.

**Comment by simo5** [comment]
You can do that by setting leeway and validity on the object you created, but your request is to add this explicitly to the constructor instead, so my question is why do you need that ?

Note that you can easily derive your own modified JWT class if it is for internal application needs:

```
class MyJWT(JWT):
def __init__(self, header=None, claims=None, jwt=None, key=None,
                   algs=None, default_claims=None, check_claims=None,
                   leeway=None, validity=None):
    super(JWT, self).__init__(header=header, claims=claims, jwt=jwt, key=key,
                                            algs=algs, default_claims=default_claims,
                                            check_claims=check_claims)
    if leeway is not None:
        self.leeway = leeway
    if valdiity is not None:
        self.validity = validity
```

**Comment by jonas-weismueller-jdas** [comment]
I Think I somehow confused myself. I thought I tested to set the validity on the object, but it did not work. I just tried to make a reproducable example, but then I could not reproduce it. It works on the object level as you stated. That's fine and all I wanted.
Sorry for the confusion.

**Comment by simo5** [comment]
No problem.
