### ISSUE TITLE
Unclear how to use JWKSet

### ISSUE THREAD

**Issue by gward** [latchset/jwcrypto#185]
Problem: I'm writing an API that signs and returns JWTs. So I have to maintain private and public keys. And I want to do things right, by rotating keys periodically. So I need to add an API endpoint where my clients can download my public keys in order to verify the JWTs that they have received from my API.

So I thought, I know, I'll do like the big commercial providers do and make that endpoint return a JWK set. I nearly coded it manually and then I realized everything I need is in jwcrypto already. Awesome!

Except... I can't figure out how to use jwcrypto.jwk.JWKSet. I've read the docs (https://jwcrypto.readthedocs.io/en/stable/jwk.html#jwcrypto.jwk.JWKSet), and the docstrings, and the source code. It's completely opaque.

Here's what I've got so far:
```
    # build a dict mapping key to JWK
    key_map: Dict[str, jwk.JWK] = {}
    for key_id in key_ids:
        with open(os.path.join(key_dir, key_id, "public.pem"), "rb") as keyfile:
            key = jwk.JWK.from_pem(keyfile.read())
            key_map[key_id] = key

    # turn that into a JWKSet for the API response
    key_set = jwk.JWKSet(key_map)
    output = key_set.export(private_keys=False)
    return flask.make_response(output, content_type="application/json")
```
That fails with
```
[2020-07-29 16:00:38,538 E 8745 fn.flasknoir.errorhandlers] GET /oidc/keys?: internal error handling request
Traceback (most recent call last):
  File "/home/gward/src/fns-auth/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gward/src/fns-auth/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gward/src/fns-auth/fn/auth/api.py", line 159, in oidc_keys
    output = key_set.export(private_keys=False)
  File "/home/gward/src/fns-auth/venv/lib/python3.7/site-packages/jwcrypto/jwk.py", line 981, in export
    return json_encode(exp_dict)
  File "/home/gward/src/fns-auth/venv/lib/python3.7/site-packages/jwcrypto/common.py", line 39, in json_encode
    return json.dumps(string, separators=(',', ':'), sort_keys=True)
  File "/usr/local/python-3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/python-3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/python-3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/python-3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type JWK is not JSON serializable
```

I'm happy to submit doc patches, but I need a bit of help. How exactly am I supposed to create a JWKSet that can then be serialized to JSON?

**Comment by gward** [comment]
First problem is that it is unclear whether JWKSet is a dict or a set. It inherits from dict, so it must be a key-value mapping, right? It only makes sense that I can initialize it from a dict that maps key ID to JWK object. But that clearly doesn't work.

So... it's a set? The docs say "A set of JWK objects." OK, I know how to initialize a set of JWK objects. Make a list of them and pass that:
```
    # load all the public keys into memory
    keys: List[jwk.JWK] = []
    for key_id in key_ids:
        with open(os.path.join(key_dir, key_id, "public.pem"), "rb") as keyfile:
            keys.append(jwk.JWK.from_pem(keyfile.read()))

    # turn that into a JWKSet for the API response
    key_set = jwk.JWKSet(keys)
    output = key_set.export(private_keys=False)
    return flask.make_response(output, content_type="application/json")
```
But that fails right in the constructor:
```
Traceback (most recent call last):
  File "/home/gward/src/fns-auth/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gward/src/fns-auth/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gward/src/fns-auth/fn/auth/api.py", line 157, in oidc_keys
    key_set = jwk.JWKSet(keys)
  File "/home/gward/src/fns-auth/venv/lib/python3.7/site-packages/jwcrypto/jwk.py", line 946, in __init__
    self.update(*args, **kwargs)
  File "/home/gward/src/fns-auth/venv/lib/python3.7/site-packages/jwcrypto/jwk.py", line 961, in update
    for k, v in iteritems(dict(*args, **kwargs)):
TypeError: cannot convert dictionary update sequence element #0 to a sequence
```

**Comment by gward** [comment]
Ahhh! Silly me, I forgot to read the _real_ docs, i.e. the unit tests. So I cloned the repo, dug up the tests, read them, and got it to work:
```
    key_set = jwk.JWKSet()
    for (_, key_dir) in _find_keys(cfg):
        with open(os.path.join(key_dir, "public.pem"), "rb") as keyfile:
            key_set.add(jwk.JWK.from_pem(keyfile.read()))

    output = key_set.export(private_keys=False)
    return flask.make_response(output, 200, {"content-type": "application/json"})
```

Thought 1: this definitely needs to be documented. From the docs and the code, it appears that I should be able to populate a JWKSet from the constructor. It appears not.

Thought 2: it ought to be possible to pass a collection of JWKs to the JWKSet constructor and get a usable JWKSet.

Thought 3: the implementation of JWKSet seems unnecessarily complex, if its entire contract is specified by the unit test. At the very least, subclassing dict seems pointless, given that it provides its own implementations of `__setitem__()`, `__contains__()`, and `__iter__()`.

I'm happy to submit patches for any of these. Please let me know what you would like!

**Comment by simo5** [comment]
Sorry for your woes, I would definitely love patches to the docs, especially examples, so certainly (1).

For (2) you should be able to pass in a set of JWKs to a new JWKSet this way:
`a = jwk.JWK()
 b = jwk.JWK()
 c = jwk.JWKSet({'a':a, 'b':b})`

For (3), JWKSet has evolved over time, the intention of subclassing dict was to make it look like a dict, later various methods have been added. I am open to proposals to improve the interface, but I also strongly believe in not breaking users by making incompatible changes whenever possible.

**Comment by simo5** [comment]
I think my last comment "resolved" the issue, so closing
