### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by daBrado** [latchset/jwcrypto#186]
Hi,

Is a new release coming soon?  I ran into the issue fixed by 9e29ac7b1be410e683b85fe36e2ab6271d03d100, and so currently need to install from the repo.

Thanks,

**Comment by simo5** [comment]
Yes we want to release.
I was on vacation, will get to it soonish.

**Comment by simo5** [comment]
Done and cut the tarball.

@tiran can you please provide the additional collaterals (wheels, .asc files) ?

**Comment by daBrado** [comment]
Great, thanks much!

In case you didn't notice, though, it appears the docs at https://jwcrypto.readthedocs.io/ haven't been updated.
