### ISSUE TITLE
Empty claims raises error on make_signed_token

### ISSUE THREAD

**Issue by daBrado** [latchset/jwcrypto#187]
If one creates a JWT with an empty claims (`{}`), `make_signed_token` errors out as it gets a claims of `None`.

This would appear to be due to `JWT.__init__` setting `self.claims` on if `claims` evaluates to false, as opposed to on `if claims is not None`.

Should that be changed, or was this on purpose?  (I don't notice in the spec that claims *must* have any key/values specified; I'd expect empty claims to be valid.)

**Comment by simo5** [comment]
So you what you are trying to do is to have a payload of '{}' ?
This doesn't appear to be against spec indeed ... investigating

**Comment by simo5** [comment]
@daBrado can you check he PR and let me know if this addresses your issue fully ?

**Comment by daBrado** [comment]
Yes, that works fine for me.  Thanks much!
