### ISSUE TITLE
LGPL is very restrictive  

### ISSUE THREAD

**Issue by yashsamit** [latchset/jwcrypto#190]
Please use BSD/Apache/MIT

**Comment by simo5** [comment]
Please argument more, or I will close as trolling.

**Comment by yashsamit** [comment]
This is your repo and your work!

But

https://softwareengineering.stackexchange.com/questions/81947/why-is-jquery-released-under-mit-and-not-lgpl

LGPL is "infectuous", which means if you use it, you risk having to (L)GPL your own work too. GPL (and, depending on the circumstances, LGPL as well) practically excludes usage in a closed-source project.

Also, we LGPL for compiled libraries and not for a python lib which is using source. We can't compile and use it as a library. So this license is invalid for such projects as per my understanding.

**Comment by simo5** [comment]
Thank you for your opinion.
