### ISSUE TITLE
Custom JSON Encoder for JWT

### ISSUE THREAD

**Issue by Otetz** [latchset/jwcrypto#191]
I didn't find any way to use custom JSON Encoder to make JWT. Is it possible?

**Comment by simo5** [comment]
What is a custom JSON Encoder ?
Can you describe what you are trying to do ?

**Comment by Otetz** [comment]
I need to store in claims some UUIDs and DateTime. This types not supported by standard `json_encode` function.

**Comment by simo5** [comment]
So you need to add custom claims ?
Have you checked the examples here: https://jwcrypto.readthedocs.io/en/latest/jwt.html#examples
You can store whatever you want in the claims
You can also use the defaults_claims parameter to set default claims.

```
  >>> from jwcrypto import jwt, jwk
  >>> key = jwk.JWK(generate='oct', size=256)
  >>> Token = jwt.JWT(header={"alg": "HS256"}, claims={"my-claim": "Custom Input"})
  >>> Token.make_signed_token(key)
  >>> Token.serialize()
  'eyJhbGciOiJIUzI1NiJ9.eyJteS1jbGFpbSI6IkN1c3RvbSBJbnB1dCJ9.tTmf2M1N_bF2FecO4u3Bp9EKCvTJ23dq0UJciMC1TQc'
```

**Comment by Otetz** [comment]
My point not about custom claims. See:
```
>>> from jwcrypto import jwt, jwk
>>> from uuid import UUID
>>> key = jwk.JWK(generate='oct', size=256)
>>> Token = jwt.JWT(header={"alg": "HS256"}, claims={"user_id": uuid4()})
...
TypeError: Object of type UUID is not JSON serializable
```

**Comment by simo5** [comment]
Otetz,
you can easily use str(uuid4()), json requires strings or integers as data, you can't use native python objects unless they support string serialization natively.
This is an issue with your choice of objects not an issue with JWCrypto.
Just use str() or whatever serialization is appropriate like base64 encoding to serialize whatever data you want to put into a JWT.

**Comment by simo5** [comment]
Just FYI, note that in claims you can pass a pre-encoded json string, you do not have to pass a dictionary.
So you can use a json encoder of your choice that does whatever serializations you need and pass a pre-encoded json string there.

HTH.
