### ISSUE TITLE
Does the JWE functionality support the "zip" header?

### ISSUE THREAD

**Issue by sbweeden** [latchset/jwcrypto#194]
More of a question than an issue at this point - does the JWE construction or decryption functionality support zip as defined here: https://tools.ietf.org/html/rfc7516#section-4.1.3

**Comment by sbweeden** [comment]
Never mind - should have looked first: https://github.com/latchset/jwcrypto/blob/master/jwcrypto/jwe.py#L196

**Comment by simo5** [comment]
Thanks for looking, because I was going to answer "no", I had totally forgot I had actually added it :-D
