### ISSUE TITLE
Encryption with PBES2-HS256+A128KW fails to 'JWK' object has no attribute 'encode'

### ISSUE THREAD

**Issue by tuukkamustonen** [latchset/jwcrypto#196]
Adjusting the example at https://jwcrypto.readthedocs.io/en/latest/jwe.html#symmetric-keys to use `PBES2-HS256+A128KW` for `alg` leads to error:

```py
...
>>> jwetoken = jwe.JWE(
        payload.encode('utf-8'),
        json_encode({"alg": "PBES2-HS256+A128KW", "enc": "A256CBC-HS512"})
    )
>>> jwetoken.add_recipient(key)
AttributeError: 'JWK' object has no attribute 'encode'
```

Unlike `_AesGcmKw._get_key()` and `_AesKw._get_key()`, `_Pbes2HsAesKw._get_key()` seems to expect raw `str`/`bytes` instead of a `JWK` instance. So this does work:

```py
>>> jwe_token.add_recipient('my-secret')
```

Why is that? Could it documented somewhere, or did I miss something?

**Comment by simo5** [comment]
I think this is just a bug.

The spec says: "The "PBES2-HS256+A128KW" and "PBES2-HS512+A256KW" algorithms defined below are used to encrypt a JWE Content Master Key using a user-supplied password to derive the key encryption key."

But it doesn't say anything about how the user-supplied password should be provided.
When I implemented this I introduced this inconsistency.

If I could go back in time I would implement a new JWK type and force use of JWK.
I think I will introduce that support now, and deprecate the current interface.

Stay tuned.

**Comment by tuukkamustonen** [comment]
FYI: I am porting old code from NodeJS to Python. It uses Node's [jose](https://www.npmjs.com/package/jose) library (old and deprecated 1.x versin) and encoding is done without specifying any algorithms. It seems to default to:

- `alg` of `PBES2-HS256+A128KW`
- `enc` of `A128CBC-HS256`

The code looks like:

```js
let key = JWK.asKey(Buffer.from('secret...'), {
    kid: '...',
    use: 'enc',
})
jwe = JWE.encrypt(JSON.stringify('data...'), key)
```

I don't know why it defaults to this (docs for the old 1.x release are no longer available), I wonder if it is suggested in the specifications, or if they just decided that this is a sensible default.

**Comment by tuukkamustonen** [comment]
Oh, if extra wishes are welcomed, how about allowing to pass `JWKSet` to `JWE.decrypt()`, too.

**Comment by simo5** [comment]
> Oh, if extra wishes are welcomed, how about allowing to pass `JWKSet` to `JWE.decrypt()` and `JWE.deserialize()`, too.

I actually have started working on this while evaluating issue 129, and this pbes2 behavior was making things more complicated already :)

**Comment by tuukkamustonen** [comment]
Ok one final related question: `JWT(jwt='...', key=key)` seems to accept only `JWK` instances and not raw keys. Is password-based encryption disallowed in JWT context, or is this just limitation of the API?

(Though, if you're removing string-based PBE secrets, and require JWK everywhere, then this limitation will become irrelevant.)

**Comment by simo5** [comment]
Limitation of JWT

**Comment by simo5** [comment]
@tuukkamustonen PTAL #197, kiitos

**Comment by simo5** [comment]
Kiitos ja Hyvää Joulua!

**Comment by tuukkamustonen** [comment]
Thanks, you too. Merry Christmas and a happy New Year!

(Though, you _do_ make me wonder about your name and background 🤔)

**Comment by simo5** [comment]
I've been very tempted through this issue to reply to you in Finnish, though it is now very rusty :-)
Yhdysvallat pakolainen! :-P
