### ISSUE TITLE
JWCrypto allows creation of invalid JWS serializations

### ISSUE THREAD

**Issue by mrbax** [latchset/jwcrypto#198]
```
>>> jwk = jwcrypto.jwk.JWK.generate( kty = 'oct' )
>>> jws = jwcrypto.jws.JWS( f'{{"exp": { int( time.time() ) + 60 }}}' )
>>> jws.add_signature( jwk, alg = 'HS256' )
>>> jws.verify( jwk, alg = 'HS256' )
>>> print( jws.serialize( True ) )
.eyJleHAiOiAxNjEwMTgxMjQ1fQ.uiq38Mpw_lM5QaEuimB7Qq0k8Oypk4svDS-MU_ndYQI
```

**Comment by simo5** [comment]
@mrbax do you think JWCrypto should raise if a protected header is not available ?

**Comment by simo5** [comment]
@mrbax or do you think that JWCrypto should syntethize a protected header with the appropriate 'alg' if one is not provided ?

I guess the latter may make sense and I am slightly inclined in that direction.

**Comment by mrbax** [comment]
I vote for synthesizing a protected header if necessary and raising an exception if not possible

**Comment by simo5** [comment]
Looking at existing code and also the JOSE Cookbook (RFC 7520 section 4.7), I think the only solution is to raise if someone requests the compact serialization and there is no protected header.
So I will go in that direction.

**Comment by simo5** [comment]
I think #199 is the best I can do for now ... PTAL

**Comment by simo5** [comment]
Adding back link to the originating issue as it has useful information:
https://github.com/jsonwebtoken/jsonwebtoken.github.io/issues/513

**Comment by mrbax** [comment]
So that's what PTAL means!  +1.  🙂
