### ISSUE TITLE
Version API

### ISSUE THREAD

**Issue by puiterwijk** [latchset/jwcrypto#22]
It would probably be very useful to have a public version number (either API version or the normal package version, although API version might be more useful).
This is mostly because when new arguments are added to existing function (example: private_only for JWKSet.export), it would be good to be able to find out if one can use it with the currently installed version.
Normally you would say "I need at least version X", but I don't think that the convenience this once function gives is worth the requirement in my opinion.

So an (API) version would be useful.

**Comment by simo5** [comment]
I am willing to consider a PR on this, but I am not planning to implement myself for now.
So I am closing the Issue.
