### ISSUE TITLE
No support for empty payloads

### ISSUE THREAD

**Issue by bbczeuz** [latchset/jwcrypto#224]
I just run into the below mentioned issue:
https://community.letsencrypt.org/t/invalid-status-value-error-msg-post-as-get-action/140556/14

JWS.add_signature does not allow empty (e.g. empty string) payloads which is requires for getting challenges via the ACME protocol.
Anybody else ran into this problem? Not sure if fixing is trivial, as I basically like jwcrypto and don't want to migrate to another module.

**Comment by simo5** [comment]
Ok, I think I can add support for empty payloads.
Do you have an example of a valid JWS accepted by ACME with an empty payload?

**Comment by simo5** [comment]
Note that JWT.io says a JWT with an empty payload is invalid ...

**Comment by bbczeuz** [comment]
Hi Simo, thanks for picking up this issue!

> Ok, I think I can add support for empty payloads.
> Do you have an example of a valid JWS accepted by ACME with an empty payload?

Empty payload:
https://datatracker.ietf.org/doc/html/rfc8555#section-7.5

Payload as '{}':
https://datatracker.ietf.org/doc/html/rfc8555#section-8.4

It's 1am here, so no more testing today ;)

**Comment by simo5** [comment]
There is no hurry, as I did not find test vectors, I add a simple test, it should work, but I would like positive confirmation that the signature generated is accepted by the ACME verifier.

**Comment by adontz** [comment]
> 
> 
> There is no hurry, as I did not find test vectors, I add a simple test, it should work, but I would like positive confirmation that the signature generated is accepted by the ACME verifier.

I can confirm that LetsEncrypt accepts the signature.

**Comment by adontz** [comment]
Thanks for fixing the bug.
Will you issue a new release anytime soon so that we can use pip to install the package, or should we install from git in near future?

**Comment by simo5** [comment]
Done
