### ISSUE TITLE
Load private / public key from PEM files

### ISSUE THREAD

**Issue by tiran** [latchset/jwcrypto#25]
PEM-encoded private key and X.509 cert files are common file formats for key material. jwcrypto should support loading private and public keys from these formats. With cryptography it is trivial, too.

I have a working implementation for Python 3, https://fedorapeople.org/cgit/cheimes/public_git/doregau.git/tree/authserver.py#n44

**Comment by simo5** [comment]
Are you thinking about adding a way to import a PEM file content in a JWK object ?
A PEM file is more than just keys, but a certificate does not map 1:1 to a JWK object.
