### ISSUE TITLE
Support RFC7515 Detached Content

### ISSUE THREAD

**Issue by titusz** [latchset/jwcrypto#256]
I would be interested in support for [JWS/CT](https://github.com/cyberphone/jws-ct) which allows to embed the signature of a JSON object into the JSON object itself by using deterministic JSON serialization and then stripping the payload from the serialized JWS token. See [RFC7515 Appendix F.](https://datatracker.ietf.org/doc/html/rfc7515#appendix-F). A python package for the required JCS canonicalization [RFC8259](https://tools.ietf.org/html/rfc8259) is available at https://pypi.org/project/jcs/ . Albeit I don´t think that `jwcrypto` would necessarily be required to support JCS canonicalization internally. It would be enough if `JWS.verify` would add an optional keyword argument to pass in a custom payload (the signature stripped and JCS serialized JSON message).

**Comment by simo5** [comment]
So we already support detaching the payload:
https://github.com/latchset/jwcrypto/blob/8613bae058b554bc56c484edcd59dda506982f5a/jwcrypto/tests.py#L1820

I do not see test to verify the signature with a detached payload ...
However it should just be working by doing this:
```
sig = jws.JWS()
sig.deserialize(token)
sig.payload = detached_payload
sig.verify(key)
```


Do you need any special support for JCS ?

**Comment by titusz** [comment]
Ah thank you. I did not see the `.detach_payload()` message. `sig.payload` is a property so I could not directly assign to it. But it works fine with `sig.objects['payload']  = ...`, no special JCS support needed. Thanks for this great lib.

**Comment by simo5** [comment]
> `sig.payload` is a property so I could not directly assign to it.

This looks like a deficiency.
I wonder if I would change the code to either provide an attach_payload() function or simply allow to set the property with some check that we make sure to invalidate verification if it has already been done and the payload is changed.

**Comment by simo5** [comment]
Actually I am pondering that maybe I should just provide a detached_payload=None argument to verify() so it can be used as needed without altering the jws object ...

**Comment by simo5** [comment]
@titusz would you find the interface proposed in #257 more usable in the future ?

**Comment by titusz** [comment]
> @titusz would you find the interface proposed in #257 more usable in the future ?

Yes that would definitely be a clearer interface for the use case.

**Comment by simo5** [comment]
Merged, will be in the next release.
