### ISSUE TITLE
Json Sorted Keys

### ISSUE THREAD

**Issue by godylockz** [latchset/jwcrypto#260]
Should probably not sort keys in `json_encode(string):` if the parser requires it to be in a specific order.
https://github.com/latchset/jwcrypto/blob/48f6234713bc0da46a947c543c02a86adda080aa/jwcrypto/common.py#L33
The only way to currently avoid this is by inputting a json string as `json_decode(string)` does not sort the keys.

**Comment by eirnym** [comment]
Which parser require keys in specific order?
Json nature is no key order at all and a parser should not rely on any specific order

**Comment by simo5** [comment]
@godylockz do you have an actual example where this is an issue?

**Comment by godylockz** [comment]
I 100% agree with all comments about this being on the parsers fault as it should not matter about the sorting of the keys...

The parser in the example did some weird splitting of the json and lead to issues ...
```python
token_head=auth_cookie.split(".")[0]
if len(token_head)%4!=0:
  no_equal_adder=4-len(auth_cookie.split(".")[0])%4
  equal_adder=no_equal_adder*"="  
  token_head=token_head+equal_adder
decoded_token=base64.urlsafe_b64decode(token_head).decode('utf-8')
url=decoded_token.split('"jku"')[1].lstrip(":").rstrip("}").strip('"')
if '"' in url:
  url=url.replace('"',"")
url=url.strip('\n')
url=url.strip()
print(len(url))
```

I noticed this as I was getting different results creating a JWT token via jwt.io and using this python cryptographic package. It all came down to how the headers were sorted.

The correct implementation shouldn't matter if its sorted or not, therefore it wouldn't hurt by removing the sorting to begin with in this library.

Wanted to let you know this, I have a way around this since the package only sorts headers depending on the type of data.

**Comment by godylockz** [comment]
@simo5 Obviously. But the code still shouldn't be sorting the headers. If you didn't have any intention of fixing this, shouldn't have asked for insecure json parser example.

**Comment by simo5** [comment]
Sorry @godylockz but I do not think there is anything to fix at this point.
I was asking for an example of *legitimate* code that could have issues.
I do not consider this example legitimate, as the bug is in the example not in jwcrypto.
