### ISSUE TITLE
New release pretty please?

### ISSUE THREAD

**Issue by jusdino** [latchset/jwcrypto#271]
Hey, I couldn't find a discrete way to reach out to the maintainers privately.

Any chance we can publish a 1.1.1 or so release that includes the `kid` fix? I'm pretty anxious to get that fix pulled into my project.

**Comment by simo5** [comment]
Uhm yeah, meant to make a small patch and then release 1.1.1 and then got distracted.

**Comment by simo5** [comment]
Done:
https://github.com/latchset/jwcrypto/releases/tag/v1.2.0
