### ISSUE TITLE
JWT `aud` claim does not support array of strings for checking

### ISSUE THREAD

**Issue by nonathaj** [latchset/jwcrypto#277]
The audience claim in JWT should support an array of strings

Reference: https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3

>    The "aud" (audience) claim identifies the recipients that the JWT is
   intended for.  Each principal intended to process the JWT MUST
   identify itself with a value in the audience claim.  If the principal
   processing the claim does not identify itself with a value in the
   "aud" claim when this claim is present, then the JWT MUST be
   rejected.  In the general case, the "aud" value is an array of case-
   sensitive strings, each containing a StringOrURI value.  In the
   special case when the JWT has one audience, the "aud" value MAY be a
   single case-sensitive string containing a StringOrURI value.  The
   interpretation of audience values is generally application specific.
   Use of this claim is OPTIONAL.

**Comment by simo5** [comment]
Aud as default is checked like this:
        self._check_array_or_string_claim('aud', claims)
here:
https://github.com/latchset/jwcrypto/blob/7a181049f1b0b5ca846e97156310d181c4cce8da/jwcrypto/jwt.py#L345

But later in the actual check claims is like this:
        self._check_string_claim('aud', check_claims)
here:
https://github.com/latchset/jwcrypto/blob/7a181049f1b0b5ca846e97156310d181c4cce8da/jwcrypto/jwt.py#L361

Is this the problem ?

At a very quick glance looks like a bug indeed, do you have a quick reproducer I can use as a test to fix and keep it from regressing?

**Comment by nonathaj** [comment]
Creating a test case, I realized this issue on my end.  To get around this issue in version 0.8, I was creating the `aud` for `check_claims` as an array, to match an array with a single entry (see `check2` below).  It appears I can change my `check_claims` to just be a single string and it will match a single entry from the array of `aud` (which is what I would expect).

```
from jwcrypto import jwt, jwk
import uuid

test_jwk = jwk.JWK.generate(kty="RSA", size=2048, kid=str(uuid.uuid4()))

access_jwt = jwt.JWT(header={ "alg": "PS256", }, claims={ "aud": ["12345"] })
access_jwt.make_signed_token(test_jwk)

check = jwt.JWT(check_claims={ "aud": "12345" }) # this works fine
check.deserialize(access_jwt.serialize(), test_jwk)

check2 = jwt.JWT(check_claims={ "aud": [ "12345" ] }) # this fails
check2.deserialize(access_jwt.serialize(), test_jwk)
```

**Comment by simo5** [comment]
Well I guess the question is whether check2 should succeed or not, and whether it should be legal to have multiple identities on a server and have any of them match ... in that case we should treat the array in a somewhat special way

I think supporting multiple identities may be potentially valuable in places where they want to proxy for multiple services, or support migrations from an old audience identifier to a new one without breaking as clients/services are being changed ...

If you agree this is a reasonable behavior I think we can use this issue as a RFE to support multiple identiies, and with a side effect of making check2 work

**Comment by nonathaj** [comment]
That seems reasonable to me.  There are probably some arguments about if both `aud` are arrays it should check for a single match or that all of them match.  That said, my gut would say that a single match is the most likely case.

**Comment by simo5** [comment]
Yeah a single match is definitely the expected cases, if you want to force match all of them you'll instead use string and verify over multiple iterations that each string matches.

**Comment by simo5** [comment]
@nonathaj can you check #278 ?
