### ISSUE TITLE
Import/Export consistency

### ISSUE THREAD

**Issue by npmccallum** [latchset/jwcrypto#28]
The export() methods should return a python dictionary that can be passed to json.dumpf(). Likewise, the import() methods should take a python dictionary as returned from json.loadf(). Please don't do the encoding internal to the API.

**Comment by simo5** [comment]
I do not want to break the API as there are multiple users of the current methods, would it be ok for you if we add an export_json/import_json par of functions that do what you ask ?

**Comment by simo5** [comment]
uhm import_json/export_json does not make a lot of sense given you want "not" json in input/output, but thinking some more I am not sure why you would want some other representation in python.
Can you point out a usecase please ?

**Comment by npmccallum** [comment]
Yes. Developers will often have a JSON object that contains a JOSE object.

If you are always encoding/decoding from bytes, then to embed the JOSE object in the parent JSON object you will need to parse json again unnecessarily.

**Comment by simo5** [comment]
Can you show me an example ?

**Comment by ad-m** [comment]
@simo5 , for example prepare JSON Web Key Set document as OpenID Connect needed:
> REQUIRED. URL of the OP's JSON Web Key Set [JWK] document. This contains the signing key(s) the RP uses to validate signatures from the OP. The JWK Set MAY also contain the Server's encryption key(s), which are used by RPs to encrypt requests to the Server. When both signing and encryption keys are made available, a use (Key Use) parameter value is REQUIRED for all keys in the referenced JWK Set to indicate each key's intended usage. Although some algorithms allow the same key to be used for both signatures and encryption, doing so is NOT RECOMMENDED, as it is less secure. The JWK x5c parameter MAY be used to provide X.509 representations of keys provided. When used, the bare key values MUST still be present and MUST match those in the certificate.

**Comment by simo5** [comment]
@npmccallum or @ad-m can you check out #180 ?
