### ISSUE TITLE
The import() method should be a class method

### ISSUE THREAD

**Issue by npmccallum** [latchset/jwcrypto#29]
The import() method is a kind of constructor. Please make it a class method.

**Comment by simo5** [comment]
I assume you are talking about JWKSet here, I will consider doing that as part of the conversion to dict

**Comment by simo5** [comment]
I added a new class method called 'from_json' in #33 please check it out

**Comment by simo5** [comment]
Resolced with:
e5c4cbb17bdb673ffb60abc2d43ef64cb451d9b8
