### ISSUE TITLE
1.3.0 breaks compatibility and should have been 2.0.0

### ISSUE THREAD

**Issue by nonathaj** [latchset/jwcrypto#291]
https://github.com/latchset/jwcrypto/commit/659fe723d1be917c45007dcd6efab40e3e0b7a49 is a compatibility breaking change in this library's API, as the `JWTMissingKeyID` exception is no longer thrown.  This should have been associated with a move to version 2.0.0, not 1.3.0.

Is there any chance we can roll back on this change, or add a similar feature to the version in JWS/JWE? It's unclear to me how a user is supposed to track when a signature error is due to a missing key or when it is from the myriad of other potential sources without that exception. This will lead to unnecessary work for every user of JWKSet, as they have to treat all `InvalidJWSSignature` as missing keys. Thus if they are requesting public keys from an external server (the common use case for JWTs), they will need to make that request every time.

**Comment by simo5** [comment]
I was afraid this may be the case.
Let me track this a s a bug, and see if I can find a way to still deal with it somehow.
I might find a way to bubble up a new missing key exception that JWT then re-throws as JWTMissingKeyID

**Comment by simo5** [comment]
The problem is that this may change what JWE and JWS may return as an exception a as well
but I guess a bit of subclassing may ease that pain, perhaps

**Comment by simo5** [comment]
Just note that JWTMissingKeyID has been deprecated for a long time, the thing I stopped using in this version is just JWTMissingKey.
