### ISSUE TITLE
Version 1.4 is not signed

### ISSUE THREAD

**Issue by yan12125** [latchset/jwcrypto#300]
Similar to https://github.com/latchset/jwcrypto/issues/230, I cannot find a signature for version 1.4, either. Could you consider adding a signature? Either a signed git tag or a signed file (e.g., in [GitHub release assets](https://github.com/latchset/jwcrypto/releases/tag/v1.4.0)) is fine.

**Comment by simo5** [comment]
Ah yeah I destroyed my yubikey which I used for previous signatures and forgot to use another key to do that, I will recreate the v1.4.0 tag as signed.

**Comment by simo5** [comment]
I was able to recover my yubikey ... \o/
I re-tagged the release, can you check if it is ok for you now ?

**Comment by yan12125** [comment]
It works, thanks a lot!
