### ISSUE TITLE
JWKSet doesn't allow for other keys

### ISSUE THREAD

**Issue by npmccallum** [latchset/jwcrypto#31]
The RFC explicitly allows the use of other key/value pairs in the JWKSet object. However, the library doesn't allow this. JWKSet should probably just implement the dict interface instead of the set interface.

**Comment by simo5** [comment]
JWKSet is a set because we want to preserve order and uniqueness of keys.
RFC7517 does allow other members besides keys, I will amend that.

**Comment by simo5** [comment]
I am looking at using an OrderedDict as the "keys" subdict and intercepting __setitem__ there to insure only JWK objects as elements, if everything works out the main object will be just a normal dict derived object, and will accept arbitrary elements for keys that are not "keys".
