### ISSUE TITLE
Release the current state 

### ISSUE THREAD

**Issue by spilikin** [latchset/jwcrypto#322]
Hi @simo5 is it possible to make a new release, so that current merged changes are available through the pypi? Thanks!

**Comment by simo5** [comment]
Ok will do after #324 is merged

**Comment by simo5** [comment]
Done!
See v1.5.0

**Comment by wolfskaempf** [comment]
@simo5 I suggest closing this issue. Thank you for the release!

**Comment by spilikin** [comment]
Thank you for the release! We are using it down here in Germany
