### ISSUE TITLE
JWK from a pyca (RSA|EllipticCurve)(Public|Private)Key

### ISSUE THREAD

**Issue by npmccallum** [latchset/jwcrypto#34]
You provide code to go from the JWK to the key object, but not vice versa.

**Comment by simo5** [comment]
True

**Comment by simo5** [comment]
There are _get_public_key/_get_private_key methods but they are not public, you have to access them via get_op_key()

**Comment by npmccallum** [comment]
Those don't work, I need to go the other direction.

**Comment by simo5** [comment]
So you need to import a pyca ec or rsa object ?

**Comment by simo5** [comment]
Would a .from_pyca class method, where the argument is a known pyca key object work ?

**Comment by npmccallum** [comment]
Yes.

**Comment by simo5** [comment]
See the above commit to one of my personal branches.
It depends on #32 so I will wait until I get a +1 review and I can pushthat one in before making a PR.
Also this allows you to import only RSA and EC (only the subset recognized by JWK) keys.

**Comment by simo5** [comment]
@npmccallum can you take a look at the above commit and #32 ?
