### ISSUE TITLE
Dependency to typing_extensions broken

### ISSUE THREAD

**Issue by bernhardboehmer** [latchset/jwcrypto#341]
The dependecy to typing_extension does not require a certain version (range). However, an error occurs due to a missing module of typing_extension:
 File "/usr/local/lib/python3.10/site-packages/jwcrypto/jwk.py", line 14, in <module>
    from typing_extensions import deprecated
ImportError: cannot import name 'deprecated' from 'typing_extensions' (/usr/local/lib/python3.10/site-packages/typing_extensions.py)

Please add a defined version (range) to your dependencies.

**Comment by Nekodann** [comment]
Can confirm same issue this morning

**Comment by bernhardboehmer** [comment]
We have a hard-set version of 4.4.0 for typing ext. Upgrading to 4.9.0 seems to make it. This means that setup.cfg should limit the lowest version of typing_extensions.

**Comment by simo5** [comment]
so we need >= 4.9.0 ?
I feel 1.5.4 coming :-D

**Comment by simo5** [comment]
@bernhardboehmer can you confirm which version needs to be claimed as minima?

**Comment by yan12125** [comment]
Per https://typing-extensions.readthedocs.io/en/latest/#deprecated, `deprecated` is added to `typing_extensions` in 4.5.0
