### ISSUE TITLE
user data becomes an "unorganized dictionary"

### ISSUE THREAD

**Issue by nblog** [latchset/jwcrypto#357]
```
    class UserBindings(BaseModel):
        时区: str = "UTC"
        测试1: Optional[OrderedDict[str, Union[str, int, float]]] = {
            "测试键1": "测试值1",
            "测试键2": "测试值2",
        }
        测试2: OrderedDict[str, Union[int, float]] = {
            "测试键1": "测试值1",
            "测试键2": "测试值2",
        }

    bindings = UserBindings()

    @staticmethod
    def dumps_bindings(bindings: 'UserBindings'):
        jwtBindings = \
            jwt.JWT(
                header=dict(alg="HS256"),
                claims=dict(
                    user_data=bindings.model_dump(),
                    iat=int(datetime.now(timezone("UTC")).timestamp())))
        jwtBindings.make_signed_token(jwk.JWK.from_password(SECRET_KEY))
        return jwtBindings.serialize()
```

order of 'user_data' messed up after serialize

**Comment by eirnym** [comment]
BTW:
After Python 3.7 regular dict keys are ordered

**Comment by eirnym** [comment]
[Here](https://github.com/latchset/jwcrypto/blob/main/jwcrypto/common.py#L36) keys are sorted during serialization. It's debatable if library should or should not sort keys during serialization. I see advantages of sorting in this particular library. 

I don't know if keys provided in an example are sorted or not (as I don't speak Chinese (this is my guess for the language used). If these keys are sorted and they become unsorted in the target, I'd check if collation set correctly first and ask for a change second.

**Comment by nblog** [comment]
> [Here](https://github.com/latchset/jwcrypto/blob/main/jwcrypto/common.py#L36) keys are sorted during serialization. It's debatable if library should or should not sort keys during serialization. I see advantages of sorting in this particular library.
> 
> I don't know if keys provided in an example are sorted or not (as I don't speak Chinese (this is my guess for the language used). If these keys are sorted and they become unsorted in the target, I'd check if collation set correctly first and ask for a change second.

Thanks for the reply, it gave me an idea why it was misplaced.
I'm using python 3.10 and my 'user_data' is explicitly OrderedDict, after serialize, and then being deserialized again, the order of the dictionaries in the user_data has been misplaced, so I had to store it as a string.

**Comment by eirnym** [comment]
I'd like to understand what does it mean `misplaced`. 

JSON data structure itself doesn't specify any order, json serializers and deserializers doesn't respect any order if not specified explicitly including Python from json package.

**Comment by nblog** [comment]
```


from pydantic import BaseModel
from typing import Optional, Union, OrderedDict
from jwcrypto import jwt, jwk
from json import loads, dumps

class UserBindings(BaseModel):
    test: OrderedDict[str, str] = {
        "b": "test1",
        "a": "test2",
    }

bindings = UserBindings()

jwtBindings = \
    jwt.JWT(
        header=dict(alg="HS256"),
        claims=dict(
            user_data=bindings.model_dump()))
jwtBindings.make_signed_token(jwk.JWK.from_password("TEST"))
base64Value = jwtBindings.serialize()

print(
    loads(jwt.JWT(jwt=base64Value, key=jwk.JWK.from_password("TEST")).claims)['user_data']
)

output: {'test': {'a': 'test2', 'b': 'test1'}}
```

my expected output: `{'test': {'b': 'test2', 'a': 'test1'}}`

**Comment by nblog** [comment]
For example, in a ListView, I `test` may be the list that the user adds to be displayed, so I'd prefer to display it in the order specified by the user

**Comment by simo5** [comment]
Sorry but there is no ordering guarantee in dictionaries, the only thing that matters for jwcrypto is a serialized token anyway. And in serialization we always ask json_encode for sort_keys=True

@nblog it is on your software to sort keys for display if that's what you want, jwcrypto will not do that for you, it is beyond its scope. The order in the dictionary simply does not matter for jwcrypto uses.
