### ISSUE TITLE
make leeway and validitity configurable via constructor

### ISSUE THREAD

**Issue by claeyswo** [latchset/jwcrypto#358]
Copy of https://github.com/latchset/jwcrypto/issues/179

We are using the python-keycloak library. Since they switched from python-jose to jwcrypto we can no longer configure the leeway.
A simple option would be to support setting them in the constructor. That way we can pass the leeway [here](https://github.com/marcospereirampj/python-keycloak/blob/210d57696af36704333ab4852abd0ad22ba5c4ce/src/keycloak/keycloak_openid.py#L551) as part of the kwargs.

**Comment by simo5** [comment]
You can set the leeway via the leeway setter.
You just need to change your code to do this:

```
    key = (whatever)..
    full_jwt = jwt.JWT(jwt=token)
    full_jwt.leeway = custom_leeway
    full_jwt.validate(key)
    return jwt.json_decode(full_jwt.claims)
```

**Comment by claeyswo** [comment]
Thx! I opened a PR in python-keycloak.
