### ISSUE TITLE
base64url_encode() should return "bytes"

### ISSUE THREAD

**Issue by franks42** [latchset/jwcrypto#42]
In common.py, the function base64url_encode() seems to be a convenience function that accepts both bytes and unicode-strings, utf8-encodes the latter, base64URLsafe encodes the bytes, strips any padding of trailing "=", and utf8-decodes the result to a unicode-string, which is returned.

However, base64 encoding should return bytes...

I can understand that you want a convenience function that returns a unicode-string such that you can easily assign it to a python object or attribute for json encoding later, but maybe rename the function to base64url_encode2ustr() or something like that to differentiate it from pure base64 encoding.

(sorry to be pedantic about this, but all this bytes vs str vs unicode in python2 vs python3 with all the inconsistent unicode/b64/json-encoding is so f#$%^ed up that keeping it clear seems to be the only way to keep ones sanity ;-) )

**Comment by franks42** [comment]
I copied the util-function that we use to this gist:
https://gist.github.com/franks42/4d14feff4019f419ac02c6a7ecf236f7

Seems too different an approach to submit any pull-request... please take a look and copy/borrow/steal any code or ideas from it that make sense to you.

**Comment by simo5** [comment]
I do not agree, the encoding function takes an arbitrary (binary) piece of data and returns a string.
So the encoding returns a string.
The decoding function takes a b64 "string" and decodes it to whatever arbitrary data, so it returns bytes.

That is purposeful.

**Comment by franks42** [comment]
Python3:

In [22]: type(base64.urlsafe_b64encode(b"jaja"))
Out[22]: bytes
--
Python2:

In [25]: type(base64.urlsafe_b64encode(b"jaja"))
Out[25]: str
--

base64.urlsafe_b64encode() returns bytes...

**Comment by simo5** [comment]
I know very well that base64.urlsafe_b64encode() return bytes, if I liked that I'd not need useful wrappers.
Point is, in the code we need to encode binary data into a string. Therefore I find it perfectly resonable to return a string.
What kind of problem is this causing you ?

**Comment by franks42** [comment]
I already suggested to add "2ustr" to distinguish it from the normal b64-encoding - never mind - forget it.
