### ISSUE TITLE
Utility functions for importing key files on disk?

### ISSUE THREAD

**Issue by wrouesnel** [latchset/jwcrypto#43]
A pretty standard use of this library is dealing with key files which need to be serialized/deserialized to disk. The JWK objects should either expose a constructor which can initialize them from on-disk PEM files, or else maybe some utility functionality should be provided to make this available?

A good middle-ground would be allowing directly initializing JWK's from rsa.Cryptography objects, since internally this is done anyway with functions like `JWK._rsa_pri`

**Comment by simo5** [comment]
Isn't this just a dupliucate of #25 ?

**Comment by simo5** [comment]
duplicate of #25
