### ISSUE TITLE
Current PyPy package has broken serialize() routine

### ISSUE THREAD

**Issue by wrouesnel** [latchset/jwcrypto#44]
The current *git* version is fine, but the version on PyPi is broken.

Specifically there's a typo in line 619 of `jwe.py`:
```            if 'recipiens' in self.objects:```

`serialize()` appears to work fine, but the resulting key cannot be decrypted.

EDIT: Actually it's found in the tagged release too - 
https://github.com/latchset/jwcrypto/blob/v0.2.1/jwcrypto/jwe.py#L619

**Comment by simo5** [comment]
I forgot I did not push a new release since fixing this error in master, I'll get to it soon

**Comment by simo5** [comment]
jwcrypto 0.3.0 is in pypi now, should solve this issue
