### ISSUE TITLE
setup.py doesn't mention cryptography as a requirement

### ISSUE THREAD

**Issue by ashb** [latchset/jwcrypto#69]
I notice that you have cryptography in requirements.txt but not in setup.py, so when installing this module JWK related function won't work.

Was this a concious decision so that people could use the JWT functions without needing a harder-to-install module or is there some other reason? If it's this I'll happily open a small PR to add a comment in the docs, or otherwise open one to add `install_requires` to setup.py

**Comment by simo5** [comment]
It's a bug, we'll get ti fixed
