### ISSUE TITLE
Test invalid curve points

### ISSUE THREAD

**Issue by tiran** [latchset/jwcrypto#73]
Add test cases to verify that we handle invalid curve points correctly. @simo5 was brave enough to jump head-first into OpenSSL. It looks like we are safe. Let's add some tests to be sure.

```
in cryptography load_elliptic_curve_public_numbers() calls _ec_key_set_public_key_affine_coordinates()
in that function EC_KEY_set_public_key_affine_coordinates() is called from openssl
and inside openssl the last function called in the method is: EC_KEY_check_key()
jose calls EC_KEY_check_key() too
```

**Comment by simo5** [comment]
I removed the "security issue" tag as so far we have determined we should be safe, and that tag is reserved for confirmed security issues in the code that need to be/have been addressed.

**Comment by simo5** [comment]
going to close this one, as I am confdent openssl properly checks for points and double checking is just going to make coed slow w/o benefits.
