### ISSUE TITLE
Broken link from documentation

### ISSUE THREAD

**Issue by sumitb** [latchset/jwcrypto#74]
https://github.com/latchset/jwcrypto/blob/1ad432d8b5dbdc8c35707c52c4503cb729577c60/docs/source/index.rst ends up as a 404

**Comment by simo5** [comment]
Can you tell me where you see this link in the documentation ?

**Comment by simo5** [comment]
Trying to find out how to fix it, no success so far.

**Comment by simo5** [comment]
Ok I removed the "stable" version as it was not clear what it was pointing to anyway.
I left now only master and the highest version for each major release that is relevant in some way
