### ISSUE TITLE
Lack of doc to install it under python3

### ISSUE THREAD

**Issue by ssonow** [latchset/jwcrypto#76]
It seem default is python2, you need to run : sudo apt-get install python3-jwcrypto instead

otherwise, in python3:

>>> from jwcrypto import jwk, jws
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'jwcrypto'
>>> 
KeyboardInterrupt

**Comment by simo5** [comment]
seem like distribution specific information, where would you doc this ?

**Comment by simo5** [comment]
I am going to close this as a downstream doc issue
