### ISSUE TITLE
'JWK' has no attribute 'generate'

### ISSUE THREAD

**Issue by ssonow** [latchset/jwcrypto#77]
I have tried as example, both python 2 and 3, and it throws:

>>> key = jwk.JWK.generate(kty='oct', size=256)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'JWK' has no attribute 'generate'

**Comment by simo5** [comment]
Works for me, I guess you used an old version in your distribution ?
