### ISSUE TITLE
consider re-license or dual Apache v2.0

### ISSUE THREAD

**Issue by ofek** [latchset/jwcrypto#87]
LGPLv3 may be incompatible with Apache v2.0. See:

https://github.com/rubychan/coderay/issues/25
https://softwareengineering.stackexchange.com/questions/81947/why-is-jquery-released-under-mit-and-not-lgpl

Maybe even do dual Apache v2.0/MIT like the Rust community https://github.com/sfackler/rust-postgres-macros/issues/19

Also just fyi to give you scope, jwcrypto was downloaded via pip 3473 times in the last 30 days.

bigquery
```
SELECT                                            
  details.installer.name as installer_name,       
  COUNT(*) as download_count,                     
FROM                                              
  TABLE_DATE_RANGE(                               
    [the-psf:pypi.downloads],                     
    DATE_ADD(CURRENT_TIMESTAMP(), -31, "day"),    
    DATE_ADD(CURRENT_TIMESTAMP(), -1, "day")      
  )                                               
WHERE                                             
  file.project = "jwcrypto"                       
GROUP BY                                          
  installer_name,                                 
ORDER BY                                          
  download_count DESC                             
LIMIT 20                                          
```

**Comment by simo5** [comment]
Thank you for your point, but at the moment we are fine with LGPL.
If, however, someone has some actual legal issue with it and makes a case for it we will consider a change.
