### ISSUE TITLE
Is there a way to use custom key for encryption/decryption?

### ISSUE THREAD

**Issue by inikolaev** [latchset/jwcrypto#88]
I'm trying to use this library but in my use case we load keys from our own key store. 

The problem is how would I create a JWK object to represent a key? I can see that I can generate a new key, o load it from PEM file, but that doesn't work for me. I would like to pass a string/byte array containing the key. Is that possible?

**Comment by simo5** [comment]
>>> from jwcrypto import jwk
>>> key = jwk.JWK(kty="oct", k="X6TBlwY2so8EwKZ2TFXM7XHSgWBKQJhcspzYydp5Y-o")
>>> key.export()
'{"k":"X6TBlwY2so8EwKZ2TFXM7XHSgWBKQJhcspzYydp5Y-o","kty":"oct"}'
