### ISSUE TITLE
Verification not working against WebCrypto keys

### ISSUE THREAD

**Issue by ondras** [latchset/jwcrypto#91]
This might as well be some large fuckup of mine.

What I did:

1) used WebCrypto to generate a keypair.
```
const keyOptions = {name: "ECDSA", namedCurve: "P-256"}
const signOptions = {name: "ECDSA", hash: {name: "SHA-256"}}
```

2) exported the public key as JWK:
```
{"crv":"P-256","ext":true,"key_ops":["verify"],"kty":"EC","x":"kudpCZSQcYKDOVlYAxfVyZc6NhPFKB2I6-3-Q14leqE","y":"MTynqg8ZTf2eKZ-YKsgGFg35S88De5wz5Tol4YMujHc"}
```

3) took a trivial challenge, `"a"`, converted it to a `new Uint8Array([ 97 ])` and signed with the private key. Got the following signature:
```
tOdwela6LqWd6S3acKgLKAX6VXNb3NcDN1v6RR0/nGa1t/eF6OZTSU6puq2px9r815kA4XrW5oOZDYxNL+VdAQ==
```

4) loaded the exported public key in Python:
```
key = jwk.JWK(**decoded_public_key)
```

5) created a JWS token:
```
sig = jws.JWS()
```

6) tried to verify the signature:
```
>>> sig.deserialize('{"payload":"YQ==", "signature":"tOdwela6LqWd6S3acKgLKAX6VXNb3NcDN1v6RR0/nGa1t/eF6OZTSU6puq2px9r815kA4XrW5oOZDYxNL+VdAQ=="}', key, "ES256")
```

7) got the `InvalidSignature()` exception.

Is there something I am doing fundamentally incorrect?

**Comment by simo5** [comment]
Print sig.verifylog for a clue

**Comment by simo5** [comment]
I think what you are missing is that a header is always part of a signature, so just signing a random value will never give yo a valid "jws" signature:

From RFC7515:
   JWS Signing Input
      The input to the digital signature or MAC computation.  Its value
      is ASCII(BASE64URL(UTF8(JWS Protected Header)) || '.' ||
      BASE64URL(JWS Payload)).

So even if you ahve an empty header, at the very least you need to prepend a '.' character to generate a valid JWS signature.

**Comment by simo5** [comment]
Also the signature is on the base64 of the payload, never on the raw payload.

**Comment by ondras** [comment]
@simo5, thanks for your insights. I will try this tomorrow when I get to work.

The signing process I currently use follows the WebCrypto `sign` function that accepts an ArrayBuffer. So in order to make the signature JWS-compatible, I need to prepend the "46" byte (code point for `.`) to my buffer, right?

And your next comment implies that my "a" payload would have to be
```js
("." + btoa("a")).split("").map(x => x.charCodeAt(0))
```
which is 
```js
[ 46, 89, 81, 61, 61 ]
```

Correct?
