### ISSUE TITLE
Not passing a protected header when creating a compact JWE causes KeyError

### ISSUE THREAD

**Issue by michaelboulton** [latchset/jwcrypto#92]
Minimal test case:

```python
# testcase.py
from jwcrypto.jwe import JWE
from jwcrypto.jwk import JWK

payload = "some payload text"

jwe = JWE(payload)

key = JWK.generate(kty='RSA', size=4096)

header = {
    "alg": "RSA-OAEP-256",
    "enc": "A256CBC-HS512",
    "typ": "JWE",
}

jwe.add_recipient(key, header)

serialised = jwe.serialize(compact=True)
```

```
$ python testcase.py
Traceback (most recent call last):
  File "testcase.py", line 18, in <module>
    serialised = jwe.serialize(compact=True)
  File "/home/michael/code/jwcrypto/jwcrypto/jwe.py", line 285, in serialize
    ph = json_decode(self.objects['protected'])
KeyError: 'protected'
```

It seems like this is a fairly easy fix to initialise the 'protected' key in 'objects' to `{}`, but I'm not sure if this is allowed by the JWE spec?

**Comment by simo5** [comment]
RFC 7516 explains at least 2 times that the JWE Protected Header is mandatory for the compact representation (emphasis mine):

- [section 5.1](https://tools.ietf.org/html/rfc7516#section-5.1).  Message Encryption, step 13:
        Compute the Encoded Protected Header value BASE64URL(UTF8(JWE
        Protected Header)).  If the JWE Protected Header is not present
        (**which can only happen when using the JWE JSON Serialization** and
        no "protected" member is present), let this value be the empty
        string.
- [section 5.2](https://tools.ietf.org/html/rfc7516#section-5.2).  Message Decryption, step 14
        Compute the Encoded Protected Header value BASE64URL(UTF8(JWE
        Protected Header)).  If the JWE Protected Header is not present
        (**which can only happen when using the JWE JSON Serialization** and
        no "protected" member is present), let this value be the empty
        string.

The protected header is required in the compact representation because you must always specify the "alg" and "enc" headers, and the compat representation can only carry a protected header.

**Comment by michaelboulton** [comment]
@simo5 Thanks for the clarification. It seems like there should be something similar to this in there (though with shorter lines):
```patch
diff --git a/jwcrypto/jwe.py b/jwcrypto/jwe.py
index 353820a..b1458fb 100644
--- a/jwcrypto/jwe.py
+++ b/jwcrypto/jwe.py
@@ -269,7 +269,9 @@ class JWE(object):
         if compact:
             for invalid in 'aad', 'unprotected':
                 if invalid in self.objects:
-                    raise InvalidJWEOperation("Can't use compact encoding")
+                    raise InvalidJWEOperation("Can't use {} unprotected header with compact encoding".format(invalid))
+            if 'protected' not in self.objects:
+                raise InvalidJWEOperation("Must use a protected header with compact encoding")
             if 'recipients' in self.objects:
                 if len(self.objects['recipients']) != 1:
                     raise InvalidJWEOperation("Invalid number of recipients")
```
I could make a pull request with a couple of regression tests in there if this makes sense to you?

**Comment by simo5** [comment]
Ah, yeah, that makes sense.
Please do.

**Comment by michaelboulton** [comment]
I was doing some testing and it seems like if you force the protected header to be an empty dictionary it works:
```python
# testcase.py
import json
from jwcrypto.jwe import JWE
from jwcrypto.jwk import JWK

payload = json.dumps({
    "test": "payload",
})

jwe = JWE(payload)
jwe.objects["protected"] = "{}"

private_key = JWK.generate(kty='RSA', size=4096)
public_key = JWK()
public_key.import_key(**json.loads(private_key.export_public()))

header = {
    "alg": "RSA-OAEP-256",
    "enc": "A256CBC-HS512",
    "typ": "JWE",
}

jwe.add_recipient(public_key, header)

encrypted = jwe.serialize(compact=True)

decrypted = JWE()
decrypted.deserialize(encrypted, key=private_key)

print(json.loads(decrypted.plaintext.decode("utf8")))
```
```
$ python testcase.py
{'test': 'payload'}
```
I'm guessing this is unintended behaviour? I'm not sure but it seems like it's just using the value of the unprotected header if the protected header isn't present in the encrypted token (in `JWE._get_jose_header`)

**Comment by simo5** [comment]
Uhm .. sounds like one of those unspecced corner cases :-(
I guess we need to check that at least alg and enc should be present ...

**Comment by simo5** [comment]
In 7.2.1.  General JWE JSON Serialization Syntax it says:
   [..]
   At least one of the "header", "protected", and "unprotected" members
   MUST be present so that "alg" and "enc" Header Parameter values are
   conveyed for each recipient computation.
   [..]

So checking for the "protected" member is not sufficient, we also need to check that it contains the "alg" and "enc" parameters.

**Comment by simo5** [comment]
One thing we can do if the protected header is missing is to just create one with "alg" and "enc" ... rather than requiring the user to do it ... but it is debatable if that is a good thing ...

**Comment by michaelboulton** [comment]
This should probably be in another issue, but there could be a couple of convenience wrappers called `CompactJWE` and `JSONJWE` which behave almost identically but do the validation at object creation. Then you can make sure that you're initialising the JWE with the correct parameters and can only be serialised in one way.

**Comment by simo5** [comment]
@michaelboulton maybe a oneshot convenience function for the compact serialization can be made up, I doubt a satisfactory one can be made for the JSON serialization.
