### ISSUE TITLE
Making all the exceptions inherit from JWException

### ISSUE THREAD

**Issue by michaelboulton** [latchset/jwcrypto#93]
It seems like this is just something that was missed out by accident? It would be nice if all the exceptions for JWE/JWT/etc. inherited from `JWException` in common.py so they could be caught in one except block.

**Comment by simo5** [comment]
Which Exceptions do you have in mind that are missing ?
If you can identify where exceptions have been missed I will glady fix them up where appropriate.

**Comment by michaelboulton** [comment]
All the exceptions in jwt.py and jwk.py inherit from `Exception` instead of `JWException`.
