### ISSUE TITLE
Extracting a public JWK from a private one

### ISSUE THREAD

**Issue by michaelboulton** [latchset/jwcrypto#99]
Assuming I generate a private key:
```python
private_key = JWK.generate(kty='RSA', size=4096)
```
It seems like the quickest way to get just a public version at the moment is to do this:
```python
public_key = JWK()
public_key.import_key(**json_decode(private_key.export_public()))
```
It would be good if there was a method called something like `extract_public` that had this behaviour:
```python
public_key = private_key.extract_public()
```
To make this simpler

**Comment by simo5** [comment]
What about JWK().get_public() which returns a JWK() with only public values in it ?
